backend/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }  

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'    
  end

  resources :users, only: [:show, :index] 

  resources :posts do
    resources :comments
    get 'comments', to: 'comments#index', on: :member, as: 'show_comments'
  end

  resources :topics do
    get 'posts', on: :member
  end
  
  resources :posts do
    get 'topic/:id', action: :show_topic_posts, on: :collection, as: :topic_posts
  end
  

  resources :comments
  root to: "welcome#index"
  


 
  
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

backend/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

backend/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user
  belongs_to :topic, optional: true

  after_create :associate_with_topics

  def associate_with_topics
    # Pego todas as palavras do post em minúsculas para remover os acentos
    words = remove_accents(body.downcase).split(/\W+/)

    words.each do |word|
      # Normalizo a palavra e verifico se corresponde a algum tópico existente, ignorando maiusculas ou minusculas
      normalized_word = normalize_word(word)
      topic = Topic.where('lower(titulo) = ?', normalized_word).first

      if topic
        # Associa o post ao tópico e continua a busca
        self.topic = topic
        save
      end
    end
  end

  def remove_accents(text)
    text.gsub(/[áàâãéèêíìîóòôõúùûç]/, 'a' => 'a', 'à' => 'a', 'â' => 'a', 'ã' => 'a', 'é' => 'e', 'è' => 'e', 'ê' => 'e', 'í' => 'i', 'ì' => 'i', 'î' => 'i', 'ó' => 'o', 'ò' => 'o', 'ô' => 'o', 'õ' => 'o', 'ú' => 'u', 'ù' => 'u', 'û' => 'u', 'ç' => 'c')
  end

  def normalize_word(word)
    # Remove acentos e caracteres especiais
    word.gsub(/[^0-9a-zA-Z]/, '')
  end
end

backend/app/models/topic.rb
class Topic < ApplicationRecord
  validates :titulo, presence: true, uniqueness: true  
  has_many :posts
end

backend/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :posts
  has_one_attached :profile_image
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

backend/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_post, only: %i[new create show edit update destroy]
  before_action :set_comment, only: %i[show edit update destroy]

  def index
    @comments = Comment.includes(:post).all
  end

  def show
  end

  def new
    @comment = @post.comments.build
  end

  def edit
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(@post)}
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
  
  def comment_params
    params.require(:comment).permit(:post_id, :body)
  end
  
end

backend/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, only: [:update, :destroy]
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_user, only: [:create]
 
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def create
    @post = Post.new(post_params)    
    @post.user = @user

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: t('new-post') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: t('edit_post') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: t('post_destroy') }
      format.json { head :no_content }
    end
  end

  private


  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit( :user_id, :body, :topic_id )
  end

  def set_user
    if user_signed_in?
      @user = current_user
    else
      @user = User.find_or_create_by(email: 'generic@example.com.br') do |user|
        user.name = 'artois'
        user.password = '12345567'
      end
    end
  end
end

backend/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 
  before_action :configure_account_update_params, only: [:update]
 
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :profile_image)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :profile_image)
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_image])
  end


end

backend/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_topic, only: %i[ show edit update destroy ]

  def index
    @topics = Topic.all
  end

  def show
    set_topic
  end

  def new
    @topic = Topic.new
  end

  def edit
    set_topic
  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: I18n.t('new_topic') }
      else
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  def update
    set_topic
    # topico_params = params.require(:topico).permit(:titulo)  - substituimos pelo metodo params sendo usado como parametro no if

    if @topic.update(topic_params)

      redirect_to topic_url(@topic), notice: I18n.t('edit_topic')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_url, notice: I18n.t('destroy')
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:titulo)
  end
end

backend/app/controllers/users_controllers.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

	def index
		@users = User.all
	end
end

backend/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.order(created_at: :desc).all
		@topics = Topic.all
		@random_users = User.all.sample(5) 
		@topics_with_posts = Topic.joins(:posts).distinct

	end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/comments_helper.rb
module CommentsHelper
end

backend/app/helpers/posts_helper.rb
module PostsHelper
end

backend/app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

  <p><%= comment.body %></p>

</div>

backend/app/views/comments/_form.html.erb
<%= form_with(model: [@post, Comment.new]) do |form| %>
  <% if @comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :post_id %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

backend/app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <p>
      <strong>@<%= comment.post.user.name%>: </strong>
      <%= comment.post.body %>
    </p>
      <strong>@<%= comment.user.name %></strong> comentou: 
      <h3><%= comment.body %></h3>    
    <hr>
  <% end %>
</div>

backend/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to post", @post %>
</div>

backend/app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Peeper</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  
  <%= stylesheet_link_tag "profile_img", "data-turbo-track": "reload" %>  
  <%= stylesheet_link_tag "footer", "data-turbo-track": "reload" %>  
   <%= stylesheet_link_tag "header", "data-turbo-track": "reload" %> 
  <%= javascript_importmap_tags %>
  
</head>
<header>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Helvetica+Neue&display=swap" rel="stylesheet">


  <div class="header-content">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"> 
    <div class="header-links">
        <img src="<%= asset_path('logo1.png') %>" alt="Seu Logo" class="logo-image">
        <%= link_to root_path do %>
          <span class="logo-text">Peeper</span>
        <% end %>
        <%= link_to "Log in", new_user_session_path, method: :get %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, url: root_path %>        
    </div>
  </div>  
</header>
<body>
  <%= yield %>
</body>
<footer>
  <div class="footer-content">
    <p>&copy; <%= Time.current.year %> Peeper. Todos os direitos reservados. &reg;</p>
  </div>
</footer>

</html>

backend/app/views/posts/_form.html.erb
<%= form_with(model: @post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">  
  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

backend/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

backend/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>   
    <p> <strong> @<%= post.user.name %>: </strong> <%= post.body %></p> 
    <p>
      <%= link_to "Show this post", post %>
    </p>
    <span><%= post.comments.count %> Comments</span>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

backend/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

backend/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="post-container">
  <%= link_to root_path do %>
  <i class="fas fa-chevron-left"></i>
  <%end%>
  <div class="post-actions">    
  <div class="post-menu">
    <span class="post-menu-icon">...</span>
    <div class="post-menu-options">
      <%= link_to "Edit this post", edit_post_path(@post) %>
      <%= link_to "Back to posts", posts_path %>
      <%= button_to "Destroy this post", @post, method: :delete %>
    </div>
  </div>  

  <%= render @post %> 
<hr>
 <%= link_to "Comentar", new_post_comment_path(@post), class: "btn btn-primary" %>
<h4>Comentários</h4>
<div class="comments">
  <% @post.comments.each do |comment| %>
    <div class="comment">
      <p class="comment-user"><strong>@<%= comment.user.name %></strong> comentou:</p>
      <p class="comment-body"><%= comment.body %></p>
      <hr>
    </div>
  <% end %>
</div>
</div>

backend/app/views/shared/_posts.html.erb
<div class="main-content" style="max-height: 1200px; overflow-y: auto;">
  <h1>Posts</h1>
  <%= link_to "Criar post", new_post_path, class: "btn" %>
  <% @posts.each do |post| %>
    <div class="post-box" onclick="window.location='<%= post_path(post) %>';">
      <div class="post-body">
        <p>@<%= post.user.name %></p>
        <p ><%= post.body %></p>
      </div>
    </div>       
  <% end %>
</div>

backend/app/views/shared/_topics.html.erb
<div class="sidebar">
  <h2 class="sidebar-title">Assuntos em alta</h2>
  <ul class="topic-list">
    <% @topics_with_posts.each do |topic| %>
      <li class="topic-item">
        <%= link_to topic.titulo, topic_path(topic), class: "topic-link" %>
      </li>
    <% end %>
  </ul>
</div>

backend/app/views/shared/_users.html.erb
<div class="sidebar">
  <h2 class="sidebar-title">Quem Seguir</h2>
  <ul class="topic-list">
    <% @random_users.each do |user| %>
    <li class="topic-item">
      <%= link_to user_path(user) do %>
        <%= image_tag user.profile_image, class: "profile-image" if user.profile_image.attached? %>
        <span class="username">@<%= user.name %></span>
      <% end %>
    </li>
    <% end %>
  </ul>
</div>

backend/app/views/topics/_form.html.erb
<%= form_with(model: @topic) do |form| %>
  <% if @topic.errors.any? %>
    <div style="color: red">
      <ul>
        <% @topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <label style="display: block" for="topic_titulo">Titulo</label>
    <input type="text" name="topic[titulo]" id="topic_titulo"/>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">  
  <p>
    <strong>Tópico:</strong>
    <%= topic.titulo %>
  </p>

</div>

backend/app/views/topics/edit.html.erb
<%= render "form", topic: @topic %>
<div>
 		<%= link_to "topics", topics_path %>
</div>

backend/app/views/topics/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "Novo Tópico", new_topic_path %>
<h1 style="color: #0c63e4">Tópicos</h1>
<% @topics.each do |t| %>
    <%= render t %>
    <p>
      <%= link_to "Show this topic", t %>
    </p>
<% end %>
</div>

backend/app/views/topics/new.html.erb
<%= render "form", topic: @topic %>
<div>
  <%= link_to "topics", topics_path %>
</div>

backend/app/views/topics/show.html.erb
<div class="topic-container">  
  
  
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <h4>As pessoas estão comentando</h4>
  <% @topic.posts.each do |post| %>
    <div class="post">
      <p class="post-user">@<%= post.user.name %></p>
      <p class="post-body"><%= post.body %></p>
    </div>
  <% end %>

  <div class="topic-actions">
    <%= link_to "Voltar", root_path, class: "btn" %>  
  </div>
</div>

backend/app/views/welcome/index.html.erb
<div class="container">  
  <%= render "shared/topics" %>
  <%= render "shared/posts" %>
  <%= render "shared/users" %>
</div>